baseURL = 'http://shzhe02.com/'
languageCode = 'en-us'
title = "rv's corner"
theme = 'PaperModX'
paginate = 10

[params]
env = "production"
defaultTheme = 'auto'
showtoc = true
tocopen = true
ShowBreadCrumbs = true
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
TocSide = 'right'
mainSections = ["bundles", "thoughtbooks", "misc"]
author = "Harvey Lim"
ShowAuthor = true
comments = true

[params.homeInfoParams]
Title = 'Welcome 👋'
Content = """Hi! I'm Harvey Lim. Here's a quick introduction of me:
- I am a **3rd-year university student studying at Aalto University**.
- My major is **Digital Systems and Design**, and I am minoring in **Computer Science**.
- I enjoy prototyping and tinkering with 3D printers.

This website is a small blog of sorts, with posts revolving around my interests. I hope you enjoy reading what I have created!
"""

[[params.socialIcons]]
name = 'github-simple'
url = 'https://github.com/shzhe02'

[[params.socialIcons]]
name = 'linkedin-simple'
url = 'https://www.linkedin.com/in/shzhe02/'

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Bundles"
url = "/bundles/"
weight = 2

[[languages.en.menu.main]]
name = "Thoughtbooks"
url = "/thoughtbooks/"
weight = 3

[[languages.en.menu.main]]
name = "Misc"
url = "/misc/"
weight = 4

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 28

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 29

[[languages.en.menu.main]]
name = "About"
url = "/about/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]
