baseURL = 'http://shzhe02.com/'
languageCode = 'en-us'
title = "rv's corner"
theme = 'PaperModX'
paginate = 10

[params]
defaultTheme = 'auto'
showtoc = true
tocopen = true
ShowBreadCrumbs = true
TocSide = 'right'

[params.homeInfoParams]
Title = 'Welcome 👋'
Content = """Hi! I'm Harvey Lim. Here's a quick introduction of me:
- I am a **3rd-year university student studying at Aalto University**.
- My major is **Digital Systems and Design**, and I am minoring in **Computer Science**.
- I enjoy prototyping and tinkering with 3D printers.

This website is a small blog of sorts, with posts revolving around my interests. I hope you enjoy reading what I have created!

...note to self, make this better later T-T
"""

[[params.socialIcons]]
name = 'github-simple'
url = 'https://github.com/shzhe02'

[[params.socialIcons]]
name = 'linkedin-simple'
url = 'https://www.linkedin.com/in/shzhe02/'

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]
